# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 08:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user1',
            old_name='Job',
            new_name='job',
        ),
        migrations.RemoveField(
            model_name='document',
            name='user1',
        ),
        migrations.AddField(
            model_name='document',
            name='user1',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
